---
- name: "Demo EVE-NG with ANSIBLE"
  hosts: 192.168.1.33
  gather_facts: no

  tasks:
  - name: Merge provided configuration with device configuration
    ios_vlans:
      config:
        - name: Vlan_10
          vlan_id: 10
          state: active
          shutdown: disabled