---
- name: "Demo EVE-NG with ANSIBLE"
  hosts: [all]
  gather_facts: no

  tasks:
  - name: Merge provided configuration with device configuration
    ios_vlan:
      name: Vlan_20
      vlan_id: 20
      state: present

